apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: now-playing
spec:
  rules:
    - host: now.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: now-playing
                port:
                  number: 80
