apiVersion: v1
kind: Service
metadata:
  name: now-playing
  labels:
    app: now-playing
spec:
  type: ClusterIP
  selector:
    app: now-playing
  ports:
    - name: http
      port: 80
      targetPort: 8000
